# .github/workflows/hello.yml
name: Hello World

on:
  push:                # trigger on every push to any branch
  workflow_dispatch:   # also allow manual trigger from GitHub UI

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello, GitHub Actions!"
      -name: wellome to CICD
        run:echo "wellcome, Wellcome to CICD!"
      

      - name: Show runner info
        run: |
          echo "Running on: $RUNNER_OS"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Triggered by: ${{ github.actor }}"

      - name: List files
        run: ls -la
